matrix:
  include:
    - language: node_js
      node_js:
        - node
      before_script:
        - cd clien
        - touch src/firebase/firebase.js
        - npm install

notifications:
  email: false